// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn-c6QmzfuSzBL0BLNEN6vlryU5eBeZ08',
    appId: '1:628535289874:web:ea30dd8438367fcd4f10cb',
    messagingSenderId: '628535289874',
    projectId: 'proser-67967',
    authDomain: 'proser-67967.firebaseapp.com',
    storageBucket: 'proser-67967.firebasestorage.app',
    measurementId: 'G-61QC2VDTQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA49C601MNYKgLDZZ2-dBGd92pA3UX_0fc',
    appId: '1:628535289874:android:3edd01e2315f6cc94f10cb',
    messagingSenderId: '628535289874',
    projectId: 'proser-67967',
    storageBucket: 'proser-67967.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4aq45SXrPxNmVQlgWZNXu--DGicUGgSc',
    appId: '1:628535289874:ios:57be7a24c4615e794f10cb',
    messagingSenderId: '628535289874',
    projectId: 'proser-67967',
    storageBucket: 'proser-67967.firebasestorage.app',
    iosBundleId: 'com.example.reprosalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4aq45SXrPxNmVQlgWZNXu--DGicUGgSc',
    appId: '1:628535289874:ios:57be7a24c4615e794f10cb',
    messagingSenderId: '628535289874',
    projectId: 'proser-67967',
    storageBucket: 'proser-67967.firebasestorage.app',
    iosBundleId: 'com.example.reprosalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn-c6QmzfuSzBL0BLNEN6vlryU5eBeZ08',
    appId: '1:628535289874:web:b901fe8b73338fe64f10cb',
    messagingSenderId: '628535289874',
    projectId: 'proser-67967',
    authDomain: 'proser-67967.firebaseapp.com',
    storageBucket: 'proser-67967.firebasestorage.app',
    measurementId: 'G-W6XRXCFZEZ',
  );
}
